
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  phone: 'phone',
  email: 'email',
  fullName: 'fullName',
  role: 'role',
  isVerified: 'isVerified',
  nidNumber: 'nidNumber',
  profilePhotoUrl: 'profilePhotoUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.PatientScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  dateOfBirth: 'dateOfBirth',
  bloodGroup: 'bloodGroup',
  gender: 'gender',
  address: 'address',
  allergies: 'allergies',
  medicalHistory: 'medicalHistory',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.DoctorScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  bmdcNumber: 'bmdcNumber',
  qualification: 'qualification',
  experienceYears: 'experienceYears',
  fee: 'fee',
  about: 'about',
  rating: 'rating',
  reviewCount: 'reviewCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.SpecialtyScalarFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.DoctorSpecialtyScalarFieldEnum = {
  doctorId: 'doctorId',
  specialtyId: 'specialtyId'
};

exports.Prisma.ClinicScalarFieldEnum = {
  id: 'id',
  name: 'name',
  address: 'address',
  phone: 'phone',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DoctorClinicScalarFieldEnum = {
  doctorId: 'doctorId',
  clinicId: 'clinicId'
};

exports.Prisma.AppointmentScalarFieldEnum = {
  id: 'id',
  patientId: 'patientId',
  doctorId: 'doctorId',
  clinicId: 'clinicId',
  type: 'type',
  status: 'status',
  date: 'date',
  timeSlot: 'timeSlot',
  durationMinutes: 'durationMinutes',
  reasonForVisit: 'reasonForVisit',
  cancellationReason: 'cancellationReason',
  cancelledBy: 'cancelledBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ConsultationScalarFieldEnum = {
  id: 'id',
  appointmentId: 'appointmentId',
  startTime: 'startTime',
  endTime: 'endTime',
  notes: 'notes',
  videoRoomId: 'videoRoomId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PrescriptionScalarFieldEnum = {
  id: 'id',
  consultationId: 'consultationId',
  title: 'title',
  summary: 'summary',
  medicinesText: 'medicinesText',
  adviceText: 'adviceText',
  diagnosis: 'diagnosis',
  fileUrl: 'fileUrl',
  digitalSignature: 'digitalSignature',
  issuedAt: 'issuedAt'
};

exports.Prisma.LabTestScalarFieldEnum = {
  id: 'id',
  name: 'name',
  price: 'price',
  sampleType: 'sampleType',
  tag: 'tag',
  tagColor: 'tagColor',
  description: 'description',
  prerequisites: 'prerequisites',
  deliveryTime: 'deliveryTime',
  category: 'category'
};

exports.Prisma.LabScalarFieldEnum = {
  id: 'id',
  name: 'name',
  address: 'address',
  phone: 'phone',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LabOrderScalarFieldEnum = {
  id: 'id',
  patientId: 'patientId',
  labId: 'labId',
  status: 'status',
  totalAmount: 'totalAmount',
  homeCollection: 'homeCollection',
  collectionAddress: 'collectionAddress',
  collectionSlot: 'collectionSlot',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LabOrderTestScalarFieldEnum = {
  labOrderId: 'labOrderId',
  labTestId: 'labTestId'
};

exports.Prisma.LabResultScalarFieldEnum = {
  id: 'id',
  labOrderId: 'labOrderId',
  resultSummary: 'resultSummary',
  fileUrl: 'fileUrl',
  uploadedAt: 'uploadedAt',
  uploadedBy: 'uploadedBy'
};

exports.Prisma.ReportParameterScalarFieldEnum = {
  id: 'id',
  labOrderId: 'labOrderId',
  parameterName: 'parameterName',
  value: 'value',
  unit: 'unit',
  referenceRange: 'referenceRange'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  orderType: 'orderType',
  orderId: 'orderId',
  amount: 'amount',
  gateway: 'gateway',
  transactionId: 'transactionId',
  status: 'status',
  paidAt: 'paidAt',
  refundReason: 'refundReason'
};

exports.Prisma.ReportsScalarFieldEnum = {
  id: 'id',
  patientName: 'patientName',
  testName: 'testName',
  labName: 'labName',
  reportDate: 'reportDate',
  sampleId: 'sampleId',
  age: 'age',
  gender: 'gender',
  referrer: 'referrer',
  time: 'time',
  createdAt: 'createdAt'
};

exports.Prisma.ReportParametersScalarFieldEnum = {
  id: 'id',
  reportId: 'reportId',
  name: 'name',
  result: 'result',
  unit: 'unit',
  range: 'range'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.UserRole = exports.$Enums.UserRole = {
  Patient: 'Patient',
  Doctor: 'Doctor',
  LabTech: 'LabTech',
  Nurse: 'Nurse',
  Admin: 'Admin'
};

exports.AppointmentType = exports.$Enums.AppointmentType = {
  In_person: 'In_person',
  Online: 'Online'
};

exports.AppointmentStatus = exports.$Enums.AppointmentStatus = {
  Pending: 'Pending',
  Confirmed: 'Confirmed',
  Completed: 'Completed',
  Cancelled: 'Cancelled',
  NoShow: 'NoShow'
};

exports.LabOrderStatus = exports.$Enums.LabOrderStatus = {
  Requested: 'Requested',
  AcceptedByLab: 'AcceptedByLab',
  SampleCollected: 'SampleCollected',
  Processing: 'Processing',
  Reported: 'Reported',
  Cancelled: 'Cancelled'
};

exports.OrderType = exports.$Enums.OrderType = {
  Appointment: 'Appointment',
  LabOrder: 'LabOrder'
};

exports.PaymentGateway = exports.$Enums.PaymentGateway = {
  bKash: 'bKash',
  Nagad: 'Nagad',
  SSLCommerz: 'SSLCommerz'
};

exports.PaymentStatus = exports.$Enums.PaymentStatus = {
  Pending: 'Pending',
  Paid: 'Paid',
  Failed: 'Failed',
  Refunded: 'Refunded'
};

exports.Prisma.ModelName = {
  User: 'User',
  Patient: 'Patient',
  Doctor: 'Doctor',
  Specialty: 'Specialty',
  DoctorSpecialty: 'DoctorSpecialty',
  Clinic: 'Clinic',
  DoctorClinic: 'DoctorClinic',
  Appointment: 'Appointment',
  Consultation: 'Consultation',
  Prescription: 'Prescription',
  LabTest: 'LabTest',
  Lab: 'Lab',
  LabOrder: 'LabOrder',
  LabOrderTest: 'LabOrderTest',
  LabResult: 'LabResult',
  ReportParameter: 'ReportParameter',
  Payment: 'Payment',
  Reports: 'Reports',
  ReportParameters: 'ReportParameters'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
